version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql/mydir:/mydir
      - ./mysql/datadir:/var/lib/mysql
      # 数据库还原目录 可将需要还原的sql文件放在这里
      - ./mysql/source:/docker-entrypoint-initdb.d
    environment:
      # MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      # MYSQL_DATABASE: ${MYSQL_DB}
      # MYSQL_CHARSET: ${MYSQL_CHARSET}
    ports:
      - 3306:3306